name: Projection publish

on:
  workflow_dispatch:
    inputs:
      sdkBuild:
        description: 'SDK build'
        required: true
        type: string
      targetVersion:
        description: 'Published version'
        required: false
        type: string

jobs:
  build:
  
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore /p:SdkBuild=${{ inputs.sdkBuild }} /p:TargetVersion="${{ inputs.targetVersion }}"
    - name: Build
      run: dotnet pack CsWinRTProjection/CsWinRTProjection.csproj -c Release --no-restore /clp:ErrorsOnly /p:SdkBuild=${{ inputs.sdkBuild }} /p:TargetVersion="${{ inputs.targetVersion }}"
    - name: Publish
      run: dotnet nuget push "CsWinRTProjection\bin\Release\*.nupkg" -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: WindowsProjection
        path: CsWinRTProjection/bin/Release/*.nupkg
